services:
  nginx:
    image: nginx:alpine
    container_name: cyberwise-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - cyberwise-user
      - cyberwise-lms
      - cyberwise-web

  cyberwise-user:
    image: ${USER_IMAGE}
    container_name: cyberwise-user
    restart: unless-stopped
    env_file: .env
    ports:
      - "10081:8080"
      - "10091:8090"


  cyberwise-lms:
    image: ${LMS_IMAGE}
    container_name: cyberwise-lms
    restart: unless-stopped
    env_file: .env
    ports:
      - "10082:9090"


  cyberwise-web:
    image: ${WEB_IMAGE}
    container_name: cyberwise-web
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"

  phish:
    image: ${GOPHISH_IMAGE}
    container_name: cyberwise-phish
    restart: unless-stopped
    ports:
      - "3331:3333"
      - "8050:8080"
    volumes:
      - ./phish/config.json:/opt/gophish/config.json:ro

networks:
  default:
    driver: bridge
